### ISSUE TITLE
Generic error message in Rhubarb for Spine

### ISSUE THREAD

**Issue by DanielSWolf** [DanielSWolf/rhubarb-lip-sync#34]
When Rhubarb Lip Sync for Spine is run from a JAR file (as opposed to a .class file), it fails to determine its binary directory. This results in the generic error message "Error performing lip sync for event <event name>."

To fix this, a more robust may of determining the binary directory needs to be implemented.

**Comment by Sergmarshall** [comment]
Hello) I have a I have a problem
![java_bag](https://user-images.githubusercontent.com/38035806/38243314-aec23ada-373f-11e8-9ee3-f98c3daad9eb.jpg)
Thanks for any help

**Comment by Sergmarshall** [comment]
java.lang.UnsupportedOperationException
        at java.util.AbstractCollection.add(Unknown Source)
        at com.sun.javafx.collections.ObservableSetWrapper.add(ObservableSetWrapper.java:267)
        at com.rhubarb_lip_sync.rhubarb_for_spine.SpineJson.createOrUpdateAnimation(SpineJson.kt:142)
        at com.rhubarb_lip_sync.rhubarb_for_spine.AnimationFileModel.saveAnimation(AnimationFileModel.kt:96)
        at com.rhubarb_lip_sync.rhubarb_for_spine.AnimationFileModel.access$saveAnimation(AnimationFileModel.kt:15)
        at com.rhubarb_lip_sync.rhubarb_for_spine.AnimationFileModel$$special$$inlined$map$lambda$1.invoke(AnimationFileModel.kt:60)
        at com.rhubarb_lip_sync.rhubarb_for_spine.AnimationFileModel$$special$$inlined$map$lambda$1.invoke(AnimationFileModel.kt:15)
        at com.rhubarb_lip_sync.rhubarb_for_spine.AudioFileModel$startAnimation$wrapperTask$1$1.invoke(AudioFileModel.kt:155)
        at com.rhubarb_lip_sync.rhubarb_for_spine.AudioFileModel$startAnimation$wrapperTask$1$1.invoke(AudioFileModel.kt:17)
        at com.rhubarb_lip_sync.rhubarb_for_spine.ToolsKt$runAndWait$$inlined$withLock$lambda$1.run(tools.kt:59)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        at java.lang.Thread.run(Unknown Source)

Microsoft Windows [Version 10.0.14393]
rhubarb-for-spine-1.7.1

**Comment by DanielSWolf** [comment]
I think I found the problem. If my understanding is correct, this error occurs if the JSON file doesn't contain at least one animation. As a quick workaround, create an empty dummy animation in Spine, re-export to JSON and try again.

Let me know if that fixes the problem. If so, I'll create a bugfix release.

**Comment by Sergmarshall** [comment]
I made some animations and everything is the same and with empty dummy animation

 at java.util.AbstractCollection.add(Unknown Source)
        at com.sun.javafx.collections.ObservableSetWrapper.add(ObservableSetWrapper.java:267)
        at com.rhubarb_lip_sync.rhubarb_for_spine.SpineJson.createOrUpdateAnimation(SpineJson.kt:142)
        at com.rhubarb_lip_sync.rhubarb_for_spine.AnimationFileModel.saveAnimation(AnimationFileModel.kt:96)
        at com.rhubarb_lip_sync.rhubarb_for_spine.AnimationFileModel.access$saveAnimation(AnimationFileModel.kt:15)
        at com.rhubarb_lip_sync.rhubarb_for_spine.AnimationFileModel$$special$$inlined$map$lambda$1.invoke(AnimationFileModel.kt:60)
        at com.rhubarb_lip_sync.rhubarb_for_spine.AnimationFileModel$$special$$inlined$map$lambda$1.invoke(AnimationFileModel.kt:15)
        at com.rhubarb_lip_sync.rhubarb_for_spine.AudioFileModel$startAnimation$wrapperTask$1$1.invoke(AudioFileModel.kt:155)
        at com.rhubarb_lip_sync.rhubarb_for_spine.AudioFileModel$startAnimation$wrapperTask$1$1.invoke(AudioFileModel.kt:17)
        at com.rhubarb_lip_sync.rhubarb_for_spine.ToolsKt$runAndWait$$inlined$withLock$lambda$1.run(tools.kt:59)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        at java.lang.Thread.run(Unknown Source)

**Comment by DanielSWolf** [comment]
I'm afraid I can't reproduce the error you're getting. My guess is that there's either something unexpected in your JSON file, or your JVM behaves differently from mine.

Could you attach the Spine JSON file you're using, along with all images and sound files? Just create a ZIP file with the entire directory structure. This should help me reproduce the behavior you're getting.

Also, could you tell me the exact JVM version you're using? (Execute `java -version`)

**Comment by rich-earth** [comment]
Hi, 

Getting same error / stack trace too.
OSX 10.13.4 
Spine 3.7.1.4
rhubarb-for-spine-1.7.1.jar
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
[rhubarb_spine_test.zip](https://github.com/DanielSWolf/rhubarb-lip-sync/files/1890580/rhubarb_spine_test.zip)

Thanks!

**Comment by rich-earth** [comment]
Update: 
It works if in Spine you add the dialog text to the String property of the event (in setup mode).   I thought this was optional so had left it out..

**Comment by DanielSWolf** [comment]
Thank you for the detailed information! I'll fix this as soon as I find some time. And, yes, the dialog text should be completely optional!

**Comment by DanielSWolf** [comment]
I found the problem! It is a bug in my code (as expected). The real mystery was why it works on my machine. Turns out it's a [bug in the programming language](https://youtrack.jetbrains.com/issue/KT-9959) that would make it work in some cases, when really it should always have failed. I'll have a fix ASAP.

**Comment by DanielSWolf** [comment]
I believe I've fixed the issue. @Sergmarshall, @rich-earth: Please replace the JAR file in your Rhubarb installation with the JAR file contained within the attached ZIP file. Let me know whether that fixes your problems! If so, I'll make an official bugfix release.

[rhubarb-for-spine-1.7.1.jar.zip](https://github.com/DanielSWolf/rhubarb-lip-sync/files/1896416/rhubarb-for-spine-1.7.1.jar.zip)

**Comment by Sergmarshall** [comment]
the plugin is working!
thank you!

**Comment by rich-earth** [comment]
Thanks
